[helpers]

[hyprland.files]
"hypr/hyprland.conf" = "~/.config/hypr/hyprland.conf"
"hypr/cleanup_after_start.sh" = "~/.config/hypr/cleanup_after_start.sh"
"hypr/fonts.conf" = "~/.config/fontconfig/fonts.conf"
"hypr/portal.sh" = "~/.config/hypr/portal.sh"

[hyprland.variables]
inactive_border = "2B2937"
active_border = "F5F4F9"
mouse_sensitivity = 0
sans_font = "SF Pro Display"
serif_font = "New York"
mono_font = "FiraCode Nerd Font"

# Local variables:
# main_monitor
# main_height
# main_width
# secondary_monitor
# keyboards
# mouse_sensitivity
# secondary_sink
# active_screenshot_keybind
# area_screenshot_keybind
# all_screenshot_keybind

[hyprpaper]
depends = ["hyprland"]

[hyprpaper.files]
"hypr/hyprpaper.conf" = "~/.config/hypr/hyprpaper.conf"

# Local variables:
# main_wallpaper
# secondary_wallpaper

[alacritty]
depends = ["hyprland"]

[alacritty.files]
"alacritty/alacritty.yml" = "~/.config/alacritty/alacritty.yml"
"alacritty/tokyonight_storm.yml" = "~/.config/alacritty/tokyonight_storm.yml"

[alacritty.variables]
term_padding = 12
term_font_size = 10


[eww]
depends = ["hyprland"]

[eww.files]
"eww/eww.yuck" = "~/.config/eww/eww.yuck"
"eww/eww.scss" = "~/.config/eww/eww.scss"
"eww/audio.sh" = "~/.config/eww/audio.sh"
"eww/iphone.sh" = "~/.config/eww/iphone.sh"


[neovim.files]
"nvim/init.lua" = "~/.config/nvim/lua/user/init.lua"
"nvim/options.lua" = "~/.config/nvim/lua/user/options.lua"
"nvim/mappings.lua" = "~/.config/nvim/lua/user/mappings.lua"
"nvim/plugins/user.lua" = "~/.config/nvim/lua/user/plugins/user.lua"

[wezterm]
depends = ["hyprland"]

[wezterm.files]
"wezterm.lua" = "~/.config/wezterm/wezterm.lua"

[wezterm.variables]
term_font_size = 10
